version: '3.8'

services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "8000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - .:/app

volumes:
  mongo_data:
